### ISSUE TITLE
Segmentation fault during contract compilation

### ISSUE THREAD

**Issue by Pafaul** [everx-labs/TVM-Solidity-Compiler#31]
This error occured during compilation of contract lilbot.sol (attached in zip archive).
![solc_bug](https://user-images.githubusercontent.com/18599919/108589327-ddd12480-736e-11eb-873b-42610a333941.png)
Used debot interfaces: https://github.com/tonlabs/ton-labs-contracts/tree/master/debots
Code was written at Windows 10 machine, then transferred to Ubuntu 18.04 server machine using SFTP (in case it is encoding issue).
Used solidity compiler version: 0.36.0+commit.5914224a.mod.Linux.g++

Problem is repeatable. If you need additional info - please contact me.

[lilbot_bug.zip](https://github.com/tonlabs/TON-Solidity-Compiler/files/6014421/lilbot_bug.zip)

**Comment by Pafaul** [comment]
Upd 1: if you remove function ```onError``` than segmentation fault error does not appear.
Upd 2: After some workaround, modified this contract so solc works correctly (lilbot.2.sol, log of build: lilbot.2.log) and two versions with segmentation fault (lilbot.1.sol and lilbot.3.sol)
All files are in repo: https://github.com/Pafaul/lilbot-solc-bug/tree/master

**Comment by SilkovAlexander** [comment]
Yeah thsats a bug thank you. There is a bug in extMsg call when you don't attach time or expire, it will be fixed in the next version of the compiler.
Now you can get around this error by creating message as a cell and send it manually:
TvmCell cell = tvm.buildExtMsg({abiVer: 1, callbackId: 0, onErrorId: 0, dest: addr, time: 0x123, call: {Foo.bar, 228, 69}, sign: true});
tvm.sendrawmsg(cell, 1);

**Comment by SilkovAlexander** [comment]
Bug was fixed and the latest version of the compiler (0.38.2) compiles all contracts from your repo
